// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jotwffwmmfubaawfnwrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvdHdmZndtbWZ1YmFhd2Zud3JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MTEyNjQsImV4cCI6MjA1OTM4NzI2NH0.d-bxtCPYJhhP12kyriJlPdtwd-bbrpBJ5lvxWv8fmhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);